# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='title',
            field=models.CharField(max_length=48),
        ),
    ]
