# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200107_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
