# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-08 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_form_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_form',
            old_name='message',
            new_name='content',
        ),
    ]
