# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-08 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200108_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_Form',
            new_name='Message',
        ),
    ]
