# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200108_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
