# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200108_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2019-10-10 08:00:00'),
            preserve_default=False,
        ),
    ]
